version: '3'
services:
  web:
    build: .
    container_name: puroen-front
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: npm run serve
    tty: true
    stdin_open: true

